In [3]:
import torch
from torch import nn, optim

In [32]:
torch.manual_seed(42)
X = 2 * torch.rand(100)
y = 4 + 3 * X + torch.randn(100) * 0.5

# Transform from shape (100,) to (100, 1) to be valid for the model
X = X.reshape(-1, 1)
y = y.reshape(-1, 1)

# Create a model that takes in 1 feature per data point and outputs 1 feature per data point
model = nn.Linear(in_features=1, out_features=1)

# Initially it has random weight and bias values
print(model.weight)
print(model.bias)

# Create the optimizer that does the gradient descent for us
optimizer = optim.SGD(model.parameters(), lr=0.05)

# Create a loss function (instead of implementing myself)
loss_function = nn.MSELoss()


for epoch in range(1000):
  pred = model(X) # 1. Calculate predictions
  loss = loss_function(pred, y) # 2. Calculate loss
  loss.backward() # Calculate dw and db
  optimizer.step() # Update w and b
  optimizer.zero_grad() # Clean up the gradients, to start fresh on the next iter

print(f'Model weight after gradient descent: {model.weight}')
print(f'Model bias after gradient descent: {model.bias}')

Parameter containing:
tensor([[0.1447]], requires_grad=True)
Parameter containing:
tensor([-0.2590], requires_grad=True)
Model weight after gradient descent: Parameter containing:
tensor([[2.8846]], requires_grad=True)
Model bias after gradient descent: Parameter containing:
tensor([4.1154], requires_grad=True)
